import Link from "next/link";

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="border-b border-gray-200 bg-white">
        <div className="mx-auto flex max-w-7xl flex-col gap-3 px-4 py-3 sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8">
          <span className="text-lg font-semibold text-gray-900">Headshot Generator</span>
          <nav className="flex flex-wrap items-center gap-3">
            <Link
              href="/login"
              className="text-sm font-medium text-gray-600 hover:text-gray-900"
            >
              Sign in
            </Link>
            <Link
              href="/signup"
              className="rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-500"
            >
              Get started
            </Link>
          </nav>
        </div>
      </header>

      <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-14 lg:px-8">
        <div className="grid items-center gap-10 lg:grid-cols-2">
          <div>
            <div className="inline-flex items-center rounded-full border border-gray-200 bg-white px-3 py-1 text-xs font-medium text-gray-700 shadow-sm">
              AI headshots • Ready in minutes
            </div>
            <h1 className="mt-5 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">
              From casual selfie → professional headshot in seconds.
            </h1>
            <p className="mt-4 text-base text-gray-600 sm:text-lg">
              Upload a selfie, pick a style, and download a polished headshot for LinkedIn, resumes,
              and team pages.
            </p>

            <div className="mt-8 grid gap-3 sm:flex sm:flex-wrap sm:items-center sm:gap-4">
              <Link
                href="/signup"
                className="w-full rounded-md bg-indigo-600 px-6 py-3 text-center text-base font-semibold text-white hover:bg-indigo-500 sm:w-auto"
              >
                Get started
              </Link>
              <Link
                href="/login"
                className="w-full rounded-md border border-gray-300 bg-white px-6 py-3 text-center text-base font-semibold text-gray-700 hover:bg-gray-50 sm:w-auto"
              >
                Sign in
              </Link>
            </div>

            <p className="mt-4 text-xs leading-relaxed text-gray-500">
              Results generated by AI. Individual results may vary.
            </p>
          </div>

          <div className="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm sm:p-6">
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="overflow-hidden rounded-xl border border-gray-200">
                <div className="flex items-center justify-between border-b border-gray-200 bg-gray-50 px-4 py-2">
                  <span className="text-xs font-medium text-gray-600">Before</span>
                  <span className="text-xs text-gray-500">Selfie</span>
                </div>
                <div className="relative h-44 bg-gradient-to-br from-gray-50 to-gray-100 sm:h-56">
                  <div className="absolute inset-0 opacity-60 [background:radial-gradient(circle_at_20%_20%,rgba(0,0,0,0.08),transparent_40%),radial-gradient(circle_at_80%_30%,rgba(0,0,0,0.06),transparent_35%),linear-gradient(135deg,rgba(99,102,241,0.08),rgba(0,0,0,0.02))]" />
                  <div className="absolute bottom-6 left-6 h-24 w-24 rounded-full bg-gray-300" />
                  <div className="absolute bottom-8 left-36 h-6 w-32 rounded-md bg-gray-200" />
                  <div className="absolute bottom-16 left-36 h-4 w-24 rounded-md bg-gray-200" />
                </div>
              </div>

              <div className="overflow-hidden rounded-xl border border-indigo-200">
                <div className="flex items-center justify-between border-b border-indigo-200 bg-indigo-50 px-4 py-2">
                  <span className="text-xs font-medium text-indigo-700">After</span>
                  <span className="text-xs text-indigo-600">Headshot</span>
                </div>
                <div className="relative h-44 bg-gradient-to-br from-indigo-50 to-white sm:h-56">
                  <div className="absolute inset-0 opacity-90 [background:radial-gradient(circle_at_30%_20%,rgba(99,102,241,0.25),transparent_45%),radial-gradient(circle_at_80%_40%,rgba(14,165,233,0.18),transparent_40%),linear-gradient(135deg,rgba(255,255,255,0.6),rgba(99,102,241,0.08))]" />
                  <div className="absolute bottom-6 left-6 h-24 w-24 rounded-full bg-indigo-200" />
                  <div className="absolute bottom-8 left-36 h-6 w-32 rounded-md bg-indigo-100" />
                  <div className="absolute bottom-16 left-36 h-4 w-24 rounded-md bg-indigo-100" />
                </div>
              </div>
            </div>

            <div className="mt-5 grid gap-3 sm:grid-cols-3">
              <div className="rounded-lg border border-gray-200 bg-white p-3">
                <p className="text-xs font-semibold text-gray-900">Upload</p>
                <p className="mt-1 text-xs text-gray-500">JPEG/PNG/WebP</p>
              </div>
              <div className="rounded-lg border border-gray-200 bg-white p-3">
                <p className="text-xs font-semibold text-gray-900">Choose style</p>
                <p className="mt-1 text-xs text-gray-500">Professional / Casual / Creative</p>
              </div>
              <div className="rounded-lg border border-gray-200 bg-white p-3">
                <p className="text-xs font-semibold text-gray-900">Download</p>
                <p className="mt-1 text-xs text-gray-500">High-quality image</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
